server:
  port: 8081
  error:
    path: "/error"

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/retro_cinema
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver